#ifndef SETTINGS_H
#define SETTINGS_H

#define RASPBERRY_PI 0
#define GPIO_PIN 2  // GPIO27 PIN13
#define RESTART_COUNTER_MAX 10
#define RECEIVE_ERROR_COUNT_MAX (500)

#define MICROTICK_NS    500000      // 500 us
#define MAKROTICK_MULT  10          //   5 ms
#define TIMEOUT_S   (0)
#define TIMEOUT_US  (60000)
#define TIMEOUT_OUT_OF_SYNC_MS (1000)
#define TIMESTAMP_DELAY_VALUE_TICKS (150U)
#define TIMESTAMP_MAX_DEVIATION_VALUE_TICKS (10U)
#define SYSLOG_NAME "slave_node"
#define EXECUTION_STATE_FILENAME "exit_state"
#define EXECUTION_STATE_STRING "last_exit_state"
#define EXECUTION_STATE_FAILURE_COUNT "failure_count"

#define CRC_POLY    0x1021
#define CRC_INIT    0xFFFF

#define THREAD_PRIORITY_RECEIVE 80 // 0=low to 99=high
#define THREAD_PRIORITY_TIMER 99 // 0=low to 99=high
#define THREAD_PRIORITY_SIGNAL_PIN 90
#define THREAD_PRIORITY_LOGGING 70

// DEBUGGING OPTIONS (PRODUCTION: SET EVERYTHING TO 0)
#define STDOUT_LOGGING_ENABLED 0
#define DEBUG_LOGGING 1
#define DEBUG_LOGGING_TIMER_HANDLER 0
#define ERROR_LOGGING 0
#define DEBUG_FIXED_LOG_FILENAME "../log/debug_log.csv"

#endif // SETTINGS_H